version: '3.8'

services:
  minio:
    image: quay.io/minio/minio:latest
    container_name: synapse-minio
    ports:
      - '${MINIO_PORT:-9000}:9000'
      - '${MINIO_CONSOLE_PORT:-9001}:9001'
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY:-minioadmin}
    volumes:
      - minio_data:/data
      - minio_config:/root/.minio
    command: server /data --console-address ":9001"
    healthcheck:
      test: [CMD, curl, -f, 'http://localhost:9000/minio/health/live']
      interval: 30s
      timeout: 20s
      retries: 3
    restart: unless-stopped
    networks:
      - synapse-network
  dragonfly:
    container_name: synapse-dragonfly
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    restart: unless-stopped
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - '6379:6379'
    volumes:
      - dragonflydata:/data
    networks:
      - dragonfly-network

volumes:
  minio_data:
    driver: local
  minio_config:
    driver: local
  dragonflydata:
    driver: local

networks:
  synapse-network:
    driver: bridge
  dragonfly-network:
    driver: bridge
